/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 engram.glb --transform
*/
import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import { exotic } from '@/templates/constants';
import Particles from './Particles';

export default function Engram(props) {
  const { nodes, materials } = useGLTF('/models/engram-transformed.glb')
  useEffect(() => {
    materials['Dark Faces'].color = new THREE.Color('#000000');
    materials['Dark Faces'].emissiveIntensity = 0;
    materials['Dark Faces'].opacity = 0.5;
  }, []);
  return (
    <group {...props} dispose={null}>
      <Particles />
      <mesh geometry={nodes.Casing.geometry} scale={1.52}>
        <MeshTransmissionMaterial background={exotic} color={exotic} transmission={.35} roughness={.2} thickness={3.5} ior={1.01} chromaticAberration={0.005} metalness={0.35} />
        <group scale={0.33}>
          <mesh geometry={nodes.Solid003.geometry} material={materials['Center Glow']} />
          <mesh geometry={nodes.Solid003_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid009.geometry} material={materials['Ring 1']} />
          <mesh geometry={nodes.Solid009_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid008.geometry} material={materials['Ring 2']} />
          <mesh geometry={nodes.Solid008_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid007.geometry} material={materials['Ring 3']} />
          <mesh geometry={nodes.Solid007_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid005.geometry} material={materials['Ring 4']} />
          <mesh geometry={nodes.Solid005_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid004.geometry} material={materials['Ring 5']} />
          <mesh geometry={nodes.Solid004_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid002.geometry} material={materials['Ring 6']} />
          <mesh geometry={nodes.Solid002_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid001.geometry} material={materials['Ring 7']} />
          <mesh geometry={nodes.Solid001_1.geometry} material={materials['Dark Faces']} />
        </group>
        <group scale={0.92}>
          <mesh geometry={nodes.Solid006.geometry} material={materials['Ring 8']} />
          <mesh geometry={nodes.Solid006_1.geometry} material={materials['Dark Faces']} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/engram-transformed.glb')
